#!/usr/bin/env python

import paramiko

host = 'remote_host'
username = 'User'
password = 'User_password'

files = ['all_files.tgz']
remote_images_path = '/homes/User'
local_path = '/User/dir_1'


# Create an SSH client
ssh = paramiko.SSHClient()

# Make sure that we add the remote server's SSH key automatically
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

# Connect to the client
ssh.connect(hostname=host, username=username, password=password)

print stdout.readlines()

sftp = ssh.open_sftp()
for file in files:
    file_remote = remote_images_path + file
    file_local = local_path + file

    print file_remote + '>>>' + file_local

    sftp.get(file_remote, file_local)

sftp.close()
ssh.close()