#!/usr/bin/env python

import paramiko

host = 'remote_host'
username = 'User'
password = 'User_password'

listof_files = ['all_files.tgz']
remote_path = '/homes/User'
local_path = '/User/dir_1'

# Create an SSH client
ssh = paramiko.SSHClient()

# Make sure that we add the remote server's SSH key automatically
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())

# Connect to the client
ssh.connect(hostname=host, username=username, password=password)

# Open sftp channel
sftp = ssh.open_sftp()
for file in files:
    #Creating full path.
    file_path_on_remote = remote_path + file
    file_path_on_local = local_path + file
    print 'Getting the files from' file_remote + 'to' + file_local
    sftp.get(file_remote, file_local)
#If control is out of loop, close the connection
sftp.close()
ssh.close()
